shows/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'shows'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^channel/new$', views.channel, name='new_channel'),
    url(r'^channel/edit$', views.channel, name='manage_channel'),
    url(r'^shows$', views.broadcast, name='broadcast'),
    url(r'^shows/new$', views.show, name='new_show'),
    url(r'^shows/(?P<show_name>[-\w]+)/edit$', views.show, name='manage_show'),
    url(r'^(?P<channel>[-\w]+)/shows/(?P<show_name>[-\w]+)$', views.watch, name='watch'),
]

vidzone/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shows.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shows/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
import os
import random
import time
import uuid


class FeaturedQuerySet(models.QuerySet):
    """Custom ``QuerySet`` to return a random instance of the base model."""

    def featured(self):
        """Return a random featured instance."""
        queryset = self.all()
        count = queryset.aggregate(count=models.Count('pk'))['count']
        if count:
            index = random.randint(0, count - 1)
            return queryset[index]
        return queryset.none()


class Channel(models.Model):
    """A collection of videos shared by a user."""

    owner = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='channel')
    name = models.CharField(_('Channel name'), max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, editable=False)
    description = models.TextField(_('Description'), blank=True)
    created = models.DateTimeField(default=timezone.now, db_index=True, editable=False)

    objects = FeaturedQuerySet.as_manager()

    class Meta:
        verbose_name = _('Channel')
        verbose_name_plural = _('Channels')
        ordering = ('name',)

    def __str__(self):
        return self.name


class License(models.Model):
    """A set of terms under which a show may be consumed."""

    name = models.CharField(_('Name'), max_length=150)
    text = models.TextField(_('Text'), blank=True)
    url = models.URLField(_('URL'), max_length=500)

    class Meta:
        verbose_name = _('Content license')
        verbose_name_plural = _('Content licenses')
        ordering = ('name',)

    def __str__(self):
        return self.name


def set_media_path(instance, filename):
    """Returns a path to the supplied show's media."""
    filename = '%s%s' % (instance.stream_name, os.path.splitext(filename)[1])
    return os.path.join('shows', instance.channel.slug, filename)

class Show(models.Model):
    """A wholesome video that visitors can enjoy."""

    # From https://en.wikipedia.org/wiki/Motion_picture_content_rating_system#Nigeria
    CR_G, CR_PG, CR_12, CR_15, CR_18 = ('G', 'PG', '12', '15', '18',)
    RATINGS = (
        (CR_G, _('Suitable for viewing by persons of all ages')),
        (CR_PG, _('Parental Guidance advised')),
        (CR_12, _('Not suitable for persons under the age of 12')),
        (CR_15, _('Not suitable for persons under the age of 15')),
        (CR_18, _('Not suitable for persons under the age of 18')),
    )

    channel = models.ForeignKey('Channel', related_name='shows')
    stream_name = models.UUIDField(default=uuid.uuid4, db_index=True, editable=False)
    title = models.CharField(_('Title'), max_length=250)
    description = models.TextField(_('Description'), blank=True)
    rating = models.CharField(_('Content Rating'), max_length=2, choices=RATINGS, default=CR_G, db_index=True)
    age_restricted = models.BooleanField(_('Enforce content rating'), default=False,
        help_text=_("Respect this show's rating, preventing underage viewers from seeing it, if neccessary."))
    content_license = models.ForeignKey('License', verbose_name=_('Content License'), 
        related_name='shows', blank=True, null=True)
    poster = models.ImageField(_('Poster'), upload_to=set_media_path, null=True, blank=True,
        help_text=_("Upload a high-resolution image to be used as this show's poster."))
    video = models.FileField(_('Video'), upload_to=set_media_path, help_text=_('Upload a video file.'))
    created = models.DateTimeField(db_index=True, null=True, editable=False, default=timezone.now)

    objects = FeaturedQuerySet.as_manager()

    class Meta:
        verbose_name = _('Show')
        verbose_name_plural = _('Shows')
        ordering = ('-created',)

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('shows:watch', (), {'channel': self.channel.slug, 'show_name': self.stream_name})

shows/forms.py
from django import forms
from django.forms import widgets
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from .models import Channel, Show


class ChannelForm(forms.ModelForm):
    """Form for creating and updating `Channels`."""

    class Meta:
        model = Channel
        fields = ('name', 'description',)
        widgets = {
            'name': widgets.TextInput(attrs={'placeHolder': 'Provide a unique name for your channel'}),
            'description': widgets.Textarea(attrs={'rows': 4}),
        }

    def __init__(self, *args, **kwds):
        self.request = kwds.pop('request')
        super().__init__(*args, **kwds)
    
    def save(self, commit=True):
        channel = super().save(commit=False)
        if not channel.slug:
            channel.slug = slugify(channel.name)
            channel.owner = self.request.user
        if commit:
            channel.save()
            self.save_m2m()
        return channel


class ShowForm(forms.ModelForm):
    """Form for creating and updating Shows."""

    class Meta:
        model = Show
        fields = ('title', 'description', 'rating', 'age_restricted', 'content_license', 'poster', 'video',)
        widgets = {
            'description': widgets.Textarea(attrs={'rows': 4}),
            'poster': widgets.FileInput(),
            'video': widgets.FileInput(),
        }

    def __init__(self, *args, **kwds):
        self.request = kwds.pop('request')
        super().__init__(*args, **kwds)

    def save(self, commit=True):
        show = super().save(commit=False)
        if not show.pk:
            show.channel = self.request.user.channel
        if commit:
            show.save()
            self.save_m2m()
        return show

shows/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import REDIRECT_FIELD_NAME, redirect_to_login as redirect_to_url
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.timezone import now
from django.utils.translation import ugettext as _
from .forms import ChannelForm, ShowForm
from .models import Channel, Show
import logging


log = logging.getLogger(__name__)


def index(request):
    all_shows = Show.objects.select_related('channel')
    selected = all_shows.order_by('-created')[:9]
    featured = all_shows.featured()
    featured_channel = Channel.objects.featured()
    return TemplateResponse(request, 'shows/index.html', 
        {'selected': selected, 'featured': featured, 'featured_channel': featured_channel})


@login_required
def broadcast(request):
    try:
        shows = request.user.channel.shows.all()
        return (redirect('shows:new_show') if not shows.exists() else 
            TemplateResponse(request, 'shows/shows.html', {'shows': shows}))
    except Channel.DoesNotExist:
        return redirect_to_url(reverse('shows:new_show'), reverse('shows:new_channel'))


@login_required
def channel(request):
    try:
        channel, new = Channel.objects.get(owner=request.user), False
    except Channel.DoesNotExist:
        channel, new = None, True
    if request.method == 'POST':
        form = ChannelForm(request.POST, request.FILES, instance=channel, request=request)
        if form.is_valid():
            channel = form.save()
            url = request.GET.get(REDIRECT_FIELD_NAME, reverse('shows:manage_channel'))
            messages.success(request, _('Your Channel has been %(action)s.' % {
                'action': _('created') if new else _('updated')
            }))
            return redirect(url)
    else:
        form = ChannelForm(instance=channel, request=request)
    return TemplateResponse(request, 'shows/channel.html', {'form': form, 'channel': channel})


@login_required
def show(request, show_name=None):
    show = get_object_or_404(Show, stream_name=show_name, channel__owner=request.user) if show_name else None
    if request.method == 'POST':
        form = ShowForm(request.POST, request.FILES, instance=show, request=request)
        if form.is_valid():
            show = form.save()
            messages.success(request, _('"%(show)s" saved. You\'re ready to start watching.') % {'show': show})
            return redirect('shows:manage_show', show_name=show.stream_name)
    else:
        form = ShowForm(instance=show, request=request)
    return TemplateResponse(request, 'shows/show.html', {'form': form, 'show': show})


def watch(request, channel, show_name):
    show = get_object_or_404(Show.objects.select_related('channel'), stream_name=show_name)
    return TemplateResponse(request, 'shows/watch.html', {'show': show,})

shows/templates/shows/admin.html
{% extends "base_site.html" %}
{% load i18n %}

{% block content %}
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <ol class="breadcrumb">
        <li><a href="{% url 'shows:broadcast' %}">Home</a></li>
        {% block admin_title %}
        <li class="active">Channel</li>
        {% endblock %}
    </ol>
</div>
<div class="col-lg-9 col-md-12 col-sm-12 col-xs-12 conentsection">
    {% block admin_content %}{% endblock %}
</div>
<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 equalcol graysidebar {% block admin_page %}{% endblock %}">
    <div class="widget">
        <h2 class="heading">Manage</h2>
        <div class="categorieslist">
            <ul>
                <li><a href="{% url 'shows:manage_channel' %}">Channel</a></li>
                <li><a href="{% url 'shows:broadcast' %}">Shows</a></li>
            </ul>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
{% endblock %}

shows/templates/shows/channel.html
{% extends "shows/admin.html" %}
{% load i18n static %}

{% block title %}
{% if channel %}{% blocktrans with channel=channel.name %}Update &quot;{{ channel }}&quot;{% endblocktrans %}{% else %}{% trans "Create your Channel" %}{% endif %}
{% endblock %}

{% block admin_title %}
<li class="active">{% trans "Channel" %}</li>
{% endblock %}

{% block admin_content %}
<div class="sections">
    <h2 class="heading">
            {% if channel %}{% blocktrans with channel=channel.name %}Update &quot;{{ channel }}&quot;{% endblocktrans %}{% else %}{% trans "Create your Channel" %}{% endif %}
    </h2>
    <div class="clearfix"></div>
    <div class="row">
        {% include "partials/form_error.html" with form=form %}
        <div class="col-lg-4 col-lg-offset-1 col-md-6 col-sm-12 col-xs-12">
            <div class="avatar">
                <p>
                    Owner: {{ user.get_full_name }}<br />
                    Email: {{ user.email|urlize }}<br />
                    Phone: {{ user.phone }}
                </p>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <form method="post" enctype="multipart/form-data" action="" novalidate>
                <div class="tabsect">
                    <ul class="nav nav-tabs"></ul>
                    <div class="tab-content">
                        <div id="channel-info" class='tab-pane active'>
                            {% include "partials/form_field.html" with fld=form.name css="form-control" %}
                            {% include "partials/form_field.html" with fld=form.description css="form-control" %}
                        </div>
                    </div>
                </div>
                <div class="form-group pull-right">
                    {% csrf_token %}{% for fld in form.hidden_fields %}{{ fld }}{% endfor %}
                    <button type="submit" class="btn btn-primary backcolor">{% trans "Submit" %}</button>
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block extrabody %}
{{ form.media }}
{% endblock %}

shows/templates/shows/index.html
{% extends "base_site.html" %}
{% load i18n show_tags static %}

{% block content %}
<div class="col-lg-9 col-md-12 col-sm-12 col-xs-12 equalcol conentsection">
    <div class="sections">
        <h2 class="heading">Latest Shows</h2>
        <div class="clearfix"></div>
        <div class="row">
            {% for show in selected|slice:":6" %}
            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                <div class="videobox2">
                    <figure>
                        <a href="{{ show.get_absolute_url }}">
                            <img src='{{ show.poster.url }}' class="img-responsive hovereffect" alt="{{ show.title }}" />
                        </a>
                        <div class="vidopts">
                            <ul>
                                <li><i class="fa fa-play-circle"></i>{{ show.title }}</li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                    </figure>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="sections">
        <h2 class="heading">Featured</h2>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div class="blogpost">
                    <figure>
                        <a href="{{ featured.get_absolute_url }}">
                            <img src='{{ featured.poster.url }}' class="img-responsive hovereffect" alt="{{ featured.title }}" />
                        </a>
                        <figcaption>
                            <ul>
                                <li><i class="fa fa-clock-o"></i>{{ featured.get_rating_display }}</li>
                            </ul>
                        </figcaption>
                    </figure>
                    <div class="text">
                        <h4 class="heading"><a href="{{ featured.get_absolute_url }}">{{ featured.title }}</a></h4>
                        <p>{{ featured.description }}</p>
                        <a href="{{ featured.get_absolute_url }}" class="btn btn-primary btn-xs backcolor">Watch Now</a>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <ul class="bloglist">
                    {% for show in selected|slice:":3" %}
                    <li>
                        <div class="media">
                            <a href="{{ show.get_absolute_url }}" class="pull-left">
                                <img src='{{ show.poster.url }}' class="media-object img-responsive hovereffect" alt="{{ show.title }}" />
                            </a>
                            <div class="media-body">
                                <h4><a href="{{ show.get_absolute_url }}">{{ show.title }}</a></h4>
                                <ul>
                                    <li><i class="fa fa-calendar"></i>{{ show.created|date:"d M Y"|capfirst }}</li>
                                </ul>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- Sidebar -->
<div class="col-lg-3 col-md-6 col-sm-12 col-xs-12 equalcol blacksidebar">
    <!-- Upcoming videos -->
    <div class="widget">
        <h2 class="heading">More Shows</h2>
        <div class="carousals">
            <div id="carouselvideo" class="carousel slide" data-ride="carousel">
                {% with batches=selected|batch:3 %}
                <div class="carousel-inner">
                    {% for shows in batches %}{% if shows %}
                    <div class="item{% if forloop.first %} active{% endif %}">
                        {% for show in shows %}
                        <div class="videobox2">
                            <figure>
                                <a href="{{ show.get_absolute_url }}">
                                    <img src='{{ show.poster.url }}' class="img-responsive hovereffect" alt="{{ show.title }}" />
                                </a>
                                <div class="vidopts">
                                    <ul>
                                        <li>{{ show.title }}</li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                            </figure>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}{% endfor %}
                </div>
                <div class="carouselpagination">
                    <ol class="carousel-indicators">
                        {% for batch in batches %}
                            {% if batch|length != 0 %}
                            <li data-target="#carouselvideo" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
                            {% endif %}
                        {% endfor %}
                    </ol>
                </div>
                {% endwith %}
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <!-- Browse categories -->
    <div class="widget">
        <h2 class="heading">Categories</h2>
        <div class="categorieslist">
            <!-- TODO: Generate these -->
            <ul>
                <li><a href="#">Animals</a></li>
                <li><a href="#">Celebrities</a></li>
                <li><a href="#">Gaming</a></li>
                <li><a href="#">Music</a></li>
                <li><a href="#">Funny</a></li>
                <li><a href="#">Movies</a></li>
                <li><a href="#">Sport</a></li>
                <li><a href="#">Lifestyle</a></li>
            </ul>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
{% endblock %}

shows/templates/shows/show.html
{% extends "shows/admin.html" %}
{% load i18n static %}

{% block title %}{% if show %}{{ show.title }}{% else %}{% trans "New Show" %}{% endif %}{% endblock %}

{% block admin_title %}
<li><a href="{% url 'shows:broadcast' %}">Shows</a></li>
<li class="active">
    {% if show %}Manage - {{ show.title }}{% else %}{% trans "New Show" %}{% endif %}
</li>
{% endblock %}

{% block admin_content %}
<div class="sections">
    <h2 class="heading">
        {% if show %}{{ show.title }}{% else %}{% trans "New Show" %}{% endif %}
    </h2>
    <div class="clearfix"></div>
    <div class="row">
        {% include "partials/form_error.html" with form=form %}
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <form method="post" enctype="multipart/form-data" action="" novalidate>
                <div class="tabsect">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#basic" data-toggle="tab">Basic Info</a></li>
                        <li><a href="#content" data-toggle="tab">Content</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="basic">
                            {% include "partials/form_field.html" with fld=form.title css="form-control" %}
                            {% include "partials/form_field.html" with fld=form.description css="form-control" %}
                        </div>
                        <div class="tab-pane" id="content">
                            {% include "partials/form_field.html" with fld=form.content_license css="form-control" %}
                            {% include "partials/form_field.html" with fld=form.rating css="form-control" %}
                            {% include "partials/form_field.html" with fld=form.age_restricted css="" %}
                            {% include "partials/form_field.html" with fld=form.poster css="" %}
                            {% include "partials/form_field.html" with fld=form.video css="" %}
                            <!-- You can add your UI for the Drive/Dropbox integration here. -->
                        </div>
                    </div>
                </div>
                <div class="form-group pull-right">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary backcolor">
                        {% if show %}{% trans "Update" %}{% else %}{% trans "Save" %}{% endif %}
                    </button>
                    {% if show.get_mode_display == "Private" %}
                    <a href="{% url 'shows:invite' show_name=show.stream_name %}" class="btn btn-default" rel="colorbox">
                        {% trans "Send Invites" %}
                    </a>
                    {% endif %}
                </div>
                <div class="clearfix"></div>
            </form>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="videobox2">
                {% if show %}{% include "shows/partials/video.html" with show=show %}{% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrabody %}
{% if show %}
<script src="https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js"></script>
<script src='{% static "js/video-player.js" %}'></script>
{% endif %}
{% endblock %}

shows/templates/shows/shows.html
{% extends "shows/admin.html" %}
{% load i18n static %}

{% block title %}{% trans "Go Live" %}{% endblock %}

{% block admin_title %}
<li class="active">Shows</li>
{% endblock %}

{% block admin_content %}
<div class="sections">
    <h2 class="heading">Shows</h2>
    <div class="clearfix"></div>
    <div class="form-group pull-right">
        <a href="{% url 'shows:new_show' %}" class="btn btn-primary backcolor">
            {% trans "New Show" %}
        </a>
    </div>
    {% for show in shows %}
        <div class="media"> 
            <a href="{% url 'shows:manage_show' show_name=show.stream_name %}" class="pull-left">
                <img alt="" class="media-object hovereffect" src='{{ show.poster.url }}'>
            </a>
            <div class="media-body">
                <h4 class="media-heading">
                    <a href="{% url 'shows:manage_show' show_name=show.stream_name %}">
                        {{ show.title }}
                    </a>
                </h4>
                <p>{{ show.description }}</p>
            </div>
        </div>
        <div class="clearfix"></div>
    {% endfor %}
    <br>
</div>
{% endblock %}

shows/templates/shows/watch.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block title %}{{ show.title }}{% endblock %}

{% block extrahead %}
<meta property="og:title" content="{{ show.title }}">
<meta property="og:description" content="{{ show.description }}">
<meta property="og:type" content="video.other">
<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ show.poster.url }}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
{% endblock %}

{% block content %}
<div class="col-lg-9 col-md-12 col-sm-12 col-xs-12 conentsection">
    <div class="blogdetail sections">
        <div class="videobox2 bootstrap-carousel">
            <div class="carousel">
                {% include "shows/partials/video.html" with show=show save_stats=True %}
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 videoinfo">
            <div class="row">
                {% include "shows/partials/show-info.html" with show=show %}
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 graysidebar">
    <div class="widget">
        <h2 class="heading">{% trans "Related Shows" %}</h2>
        {% include "shows/partials/related.html" with item=show %}
    </div>
    <div class="clearfix"></div>
</div>
{% endblock %}

{% block extrabody %}
<script src="https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js"></script>
<script src='{% static "js/video-player.js" %}'></script>
{% endblock %}