accounts/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import views as auth_views
from .views import register_view, verify_email

app_name = 'accounts'

urlpatterns = [
    url(r'^logout$', auth_views.logout, name='logout'),
    url(r'^reset-password$', auth_views.password_reset, 
        {'email_template_name': 'registration/password_reset_email.txt', 
         'html_email_template_name': 'registration/password_reset_email.html',
         'post_reset_redirect': reverse_lazy('accounts:reset_requested')},
        name='reset_password'),
    url(r'^reset-password/requested$', auth_views.password_reset_done, name='reset_requested'),
    url(r'^reset-password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$', 
        auth_views.password_reset_confirm, {'post_reset_redirect': reverse_lazy('accounts:reset_password_complete')},
        name='confirm_reset_password'),
    url(r'^reset-password/complete$', auth_views.password_reset_complete, name='reset_password_complete'),
    url(r'^login$', auth_views.login, name='login'),
    url(r'^register$', register_view, name='register'),
    url(r'verify/(?P<fldb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$', 
        verify_email, name='verify_email'),
]

shows/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'shows'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^channel/new$', views.channel, name='new_channel'),
    url(r'^channel/edit$', views.channel, name='manage_channel'),
    url(r'^shows$', views.broadcast, name='broadcast'),
    url(r'^shows/new$', views.show, name='new_show'),
    url(r'^shows/(?P<show_name>[-\w]+)/edit$', views.show, name='manage_show'),
    url(r'^(?P<channel>[-\w]+)/shows/(?P<show_name>[-\w]+)$', views.watch, name='watch'),
]

vidzone/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shows.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vidzone/templates/base_site.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>{% block title %}Videos, videos everywhere{% endblock %} :: VidZone</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="HandheldFriendly" content="True">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <link href='{% static "images/favicon.ico" %}' rel="icon" type="image/x-icon" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700&subset=latin" rel="stylesheet" media="screen" />
        <link href='{% static "css/bootstrap.css" %}' rel="stylesheet" media="screen" />
        <link href='{% static "css/font-awesome.min.css" %}' rel="stylesheet" media="screen" />
        <link href='{% static "css/style.css" %}' rel="stylesheet" media="screen" />
        <link href='{% static "css/colorbox.css" %}' rel="stylesheet" media="screen" />
        <!--[if lt IE 9]>
            <script src='{% static "js/html5shiv.js" %}'></script>
            <script src='{% static "js/respond.min.js" %}'></script>
        <![endif]-->
        {% block extrahead %}{% endblock %}
    </head>
    <body>
        <div class="wrapper">
            <header>
                <div class="navigationstrip bordercolor-top">
                    <div class="custom-container">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="navigation">
                                    <nav class="navbar navbar-default yamm">
                                        <div class="row">
                                            <div class="navbar-header">
                                                <button type="button" data-toggle="collapse" data-target="#navbar-collapse-1" class="navbar-toggle" role="none" tabindex="-1">
                                                    <i class="fa fa-bars fa-2x"></i>
                                                </button>
                                                <a class="navbar-brand" href='{% url "shows:index" %}'>
                                                    <img src='{% static "images/logo.png" %}' alt="WStreams" />
                                                </a>
                                            </div>
                                            <div id="navbar-collapse-1" class="navbar-collapse collapse">
                                                <ul class="nav navbar-nav navbar-right">
                                                    <li>
                                                        <form class="navbar-form navbar-search-form searchbox" role="search">
                                                            <ul class="form-group">
                                                                <li><input type="text" name="q" placeholder="Search Shows" /></li>
                                                                <li class="pull-right"><input type="submit" value="GO" /></li>
                                                            </ul>
                                                        </form>
                                                    </li>
                                                    {% if user.is_authenticated %}
                                                    <li>
                                                        <p class="navbar-btn">
                                                            <a href="{% url 'shows:broadcast' %}" class="btn btn-primary backcolor">Upload</a>
                                                        </p>
                                                    </li>
                                                    <li class="dropdown">
                                                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Profile</a>
                                                        <ul class="dropdown-menu">
                                                            <li><a href="{% url 'shows:manage_channel' %}">My Channel</a></li>
                                                            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                                                        </ul>
                                                    </li>
                                                    {% else %}
                                                    <li>
                                                        <p class="navbar-btn">
                                                            <a href="{% url 'accounts:register' %}" class="btn btn-primary backcolor">Join</a>
                                                        </p>
                                                    </li>
                                                    <li>
                                                        <a href="{% url 'accounts:login' %}">Log In</a>
                                                    </li>
                                                    {% endif %}
                                                </ul>
                                            </div>
                                        </div>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <div class="contents">
                <div class="custom-container">
                    <div class="row">
                        {% for message in messages %}
                            <div class="alert alert-dismissible alert-{{ message.tags }}" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <strong>{{ message.tags|title }}:</strong> {{ message }}
                            </div>
                            {% if forloop.last %}
                            <script>
                                var messages = document.querySelector('div[role=alert]');
                                window.setTimeout(function () { messages.style.display = 'none'; }, 5000);
                            </script>
                            {% endif %}
                        {% endfor %}
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
            <footer class="style1">
                <div class="custom-container">
                    <div class="row">
                        <div class="col-lg-10 col-md-10 col-sm-9 .col-xs-9">
                            <p class="copyrights">&copy; VidZone {% now "Y" %}. All rights reserved.</p>
                        </div>
                    </div>
                </div>
            </footer>
            <a href="#" class="pull-right gotop btn btn-primary backcolor"> <i class="fa fa-arrow-up"></i> </a>
        </div>
        <script src='{% static "js/jquery-1.11.1.min.js" %}'></script>
        <script src='{% static "js/jquery-ui.min.js" %}'></script>
        <script src='{% static "js/bootstrap.min.js" %}'></script>
        <script src='{% static "js/jquery.colorbox-min.js" %}'></script>
        {% block extrabody %}{% endblock %}
        <script src='{% static "js/functions.js" %}'></script>
        <script src='{% static "js/responsiveCarousel.js" %}'></script>
        <script src='{% static "js/responsive-paginate.js" %}'></script>
    </body>
</html>